version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: pet-store
    volumes:
      - ../mongodb-init:/docker-entrypoint-initdb.d:ro

  pet-store:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      no_cache: true
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    entrypoint: ["./scripts/wait-for-it.sh", "--timeout=60", "mongo:27017", "--", "/usr/local/bin/npm", "run", "cover:integration"]
